### ISSUE TITLE
告知タスク

### ISSUE THREAD

**Issue by hosshan** [MentorsSchool/Workshop#1]
## ToDo
- [x] 告知文の作成
- [x] 告知文のブラッシュアップ
- [x] イベント名の決定
- [x] イベント日程の決定
- [x] イベント登録フォームの作成
- [x] 告知用のイメージの作成

**Comment by hosshan** [comment]
【告知文 第一版】
Mentors School開講！！！

2018年卒以降のエンジニア志望のメンターを対象に、リクルティーングリポジトリを作りを通して良いコードを書くためのワークショップを開催します！！
リクルーティングリポジトリとは、就活の際などに企業に見せるためのソースコードやドキュメントなどをまとめたものになります！
最近では、就活の際や、インターンの応募の際に必ずと言っていいほどGitHubのアカウントを聞かれます。そんな時、他人に自信を持って見せれるリポジトリがない！！といったことがあると思います。
ワークショップでは、リポジトリを通して自分の技術力を表すために気をつけるべきポイントや、まじめにプロダクトを作ることを目的としたコードの書き方を、先輩メンターからのガチなレビューを通して学べます！！

ワークショップは、9月の中旬から2週に1度くらいの頻度で全部で6回ほど行う予定ですが、まずは7月の21日と22日に説明会を2回ほど開催したいと思います！
7月は難しいという方も、まだ就活生ではないという方も、まずは以下のフォームから参加したいかどうかなどのアンケートに答えてもらえればと思います。

**Comment by hosshan** [comment]
【イベント日程 候補】
- 21日 19:30〜
- 22日 19:30〜

### ※丸さんOKもらった

**Comment by omuomugin** [comment]
[説明会用のGoogle フォーム]

https://docs.google.com/forms/d/1cM0cs5b3OQPV_Ao8cGIwA8YIH41Cme1cEr6WFz7qwgk/viewform

**Comment by hosshan** [comment]
@Aguri アグリ先生のお力で告知用のイケてるイメージお願いできないでしょうか！！

**Comment by Aguri** [comment]
やります！

**Comment by hosshan** [comment]
イベント名：Mentors School

**Comment by Aguri** [comment]
![mentorschoolgreece](https://cloud.githubusercontent.com/assets/7918776/16543726/c469e300-411f-11e6-90aa-82637b7db7ce.png)

古代哲学者編

**Comment by hosshan** [comment]
メンターの技術を哲学する

古代ギリシャ哲学は、現在でいう哲学のみならずコーディングやアルゴリズムなどを含む学問や学究的営為の総称である。
古代ギリシャでは、リーダブルコード主義者のホシャクラテスが全ての人に読みやすいコードの書き方とは何かを説きサービスの開発の教育方法に新たな流れを巻き起こそうとしていた。
また、その頃台頭するようにアグリウスがサービスアイデア主義を唱え、メンター教育に新風を巻き起こした。
この他にも、多くのメンターの新しい学派が存在しメンター教育の歴史に大きな転換期が生まれようとしている。

**Comment by Aguri** [comment]
![mentorschoolgreece2](https://cloud.githubusercontent.com/assets/7918776/16543800/9adf9c9a-4125-11e6-9521-d3c4b925a9ea.png)
文章更新しました

**Comment by hosshan** [comment]
告知したのでClose
