### ISSUE TITLE
リマインド告知

### ISSUE THREAD

**Issue by hosshan** [MentorsSchool/Workshop#6]
## About

告知のリマインドを行う。
リマインドでは、勉強会のスケジュールや趣旨など。もっと中身に触れた内容を増やすようにする

**Comment by hosshan** [comment]
## 改善点メリットが伝わらない
- 就活をしないとリポジトリの重要性が見えない
- 就活をしない人のメリット
  - 企画能力
  - エンジニアマネジメント能力
  - グロースなどの力など

**Comment by omuomugin** [comment]
## 入れたい内容
- ワークショップの一部(できればタイトル的なものの一覧まで)
- 説明会で使うであろうスライドの前置き部分
- ターゲットを明確に伝える(現状だとみんな応募してねー的な感じ -> こういうメンターにとってプラスになるとはっきり伝える)
- あぐりとほっしゃん以外の講師の発表をしたいところ

**Comment by omuomugin** [comment]
告知文[Ver1.1]

先週お知らせした、「LiTプレゼンツ！メンターによるメンター育成の場の"LiT University"の企画第一弾"MentorsSchool"」のリマインドです。今回は、もうすこしMentorsSchoolの全貌を明らかにしていきたいと思います。

1 どんな人向けなのか。
・ まだサービスを1から作った経験がなかったり、実務での開発の流れが分からない人。
・ サービスを作るだけじゃなく、もっとコードをキレイにして黒ポロなどのテクニカルメンターになりたい人。

2 何をやるのか。
ワークショップは、9月の中旬から隔週で全6回を予定しており、2〜3ヶ月でサービスの立案から実装までを行います！
また、各ワークショップでは、講師によるLTやレビュー、また即席でチームを組んでの開発など、1人での開発では体験できない内容を用意しています。大きくは、以下になります。

・ コーディング
・ サービス開発
・ チームマネジメント
・ セルフ・マネジメント

詳しくは、添付の画像をみてください。

3 何が得られるのか。どこに生かせるのか。
・ 綺麗なコードを書く理由を理解し、レビューを受けることで、それを意識したエンジニアとしてのコードが書けるようになる。
・ サービス開発の全体像を知ることで、メンバー達にも正しいサービス開発を教えることができる。
・チームマネジメントを学ぶことでチーム開発のフローを学ぶことができる。
・ セルフ・マネジメントの仕方を知ることで、今後の人生設計をちゃんと考えることができる。
・ 逆求人イベントなどを通して内定がもらえる可能性がある。

**Comment by omuomugin** [comment]
![2016-07-14 19 54 50](https://cloud.githubusercontent.com/assets/16621708/16837412/315b20aa-49fe-11e6-8f48-3b9a0e0ec9d8.png)

**Comment by hosshan** [comment]
画像、こっちに修正
![remind_image 001](https://cloud.githubusercontent.com/assets/5677723/16846421/5a62fbac-4a27-11e6-9e6c-9025d394cf23.jpeg)

**Comment by hosshan** [comment]
タイトルつけ忘れてた
![remind_contents](https://cloud.githubusercontent.com/assets/5677723/16846760/a27d973e-4a28-11e6-89cb-7364beb1eca2.jpeg)

**Comment by omuomugin** [comment]
告知文、若干のupdate

**Comment by hosshan** [comment]
終わったから閉じる
